
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'   
  web1core:
    restart: on-failure
    build: ./core
    hostname: core
    ports:
      - '81:5000'
  web2:
    restart: on-failure
    build: ./web
    hostname: web2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - web1core
    - web2